name:                chasm
version:             0.1.0.0
github:              "maybetonyfu/chasm"
license:             BSD3
author:              "Tony Fu"
maintainer:          "tonyfu@fastmail.com"
copyright:           "2023 Tony Fu"

dependencies:
- base
- rio
- string-qq
- haskell-src-exts

library:
  source-dirs: src


executables:
  chasm:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chasm
